/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
 
 
int st;

public void circle1_click1(GButton source, GEvent event) { //_CODE_:circle1:561316:
  println("Circle clicked at: " + millis());
 for(st = 0; st < 50; st++){
  noStroke ();
  fill (random (255), random (255), random(255), 170);
  ellipse (random (0, width), random (0, height), 60, 60);
 }
 
} //_CODE_:circle1:561316:

public void button2_click1(GButton source, GEvent event) { //_CODE_:square1:656476:
  println("Square clicked at: " + millis());
  for(st = 0; st < 50; st++){
   noStroke ();
  fill (random (255), random (255), random(255), 170);
 // size(50,50,P3D);
 rect(random(0,width), random(0,height), 60,60);
 // box(random(0,width), random(0,height), random(0,height));
  }
} //_CODE_:square1:656476:

public void button3_click1(GButton source, GEvent event) { //_CODE_:triangle1:298157:
  println("Triangle clicked at: " + millis());
  for(st = 0; st < 50; st++){
   noStroke ();
  fill (random (255), random (255), random(255), 200);
  triangle(random(0,width), random(0,height), random(0,width), random(0,height), 300, 275);
  }
} //_CODE_:triangle1:298157:

public void button4_click1(GButton source, GEvent event) { //_CODE_:pause1:488433:
  println("Clear clicked at: " + millis());
  background(230);
} //_CODE_:pause1:488433:

public void button5_click1(GButton source, GEvent event) { //_CODE_:resume1:284723:
  println("Background clicked at: " + millis());
  background(random(255),random(255),random(255));
} //_CODE_:resume1:284723:

public void button6_click1(GButton source, GEvent event) { //_CODE_:resume1:284723:
  println("Save clicked at: " + millis());
  PImage partialSave = get(0,0,600,565);
  //selectInput("Select ","file");
  partialSave.save("art-#####.jpeg");
  //saveFrame("art-#####.jpeg");
} //_CODE_:resume1:284723:

//filter button
public void button7_click1(GButton source, GEvent event) { //_CODE_:resume1:284723:
  println("Filer clicked at: " + millis());
  //filter(THRESHOLD);
  filter(BLUR,5);
} //_CODE_:resume1:284723:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Random Art Generator");
  circle1 = new GButton(this, 0, 570, 80, 30);
  circle1.setText("Circle");
  circle1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  circle1.addEventHandler(this, "circle1_click1");
  square1 = new GButton(this, 90, 570, 80, 30);
  square1.setText("Square");
  square1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  square1.addEventHandler(this, "button2_click1");
  triangle1 = new GButton(this, 180, 570, 80, 30);
  triangle1.setText("Triangle");
  triangle1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  triangle1.addEventHandler(this, "button3_click1");
  pause1 = new GButton(this, 270, 570, 80, 30);
  pause1.setText("Clear");
  pause1.setLocalColorScheme(GCScheme.RED_SCHEME);
  pause1.addEventHandler(this, "button4_click1");
  resume1 = new GButton(this, 360, 570, 80, 30);
  resume1.setText("Background");
  resume1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  resume1.addEventHandler(this, "button5_click1");
  
  //Save button
  save1 = new GButton(this, 450, 570, 80, 30);
  save1.setText("Save");
  save1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  save1.addEventHandler(this, "button6_click1");
  
  
  //Filter
   filter1 = new GButton(this, 540, 570, 60, 30);
   filter1.setText("Filter");
   filter1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
   filter1.addEventHandler(this, "button7_click1");
  
}

// Variable declarations 
// autogenerated do not edit
GButton circle1; 
GButton square1; 
GButton triangle1; 
GButton pause1; 
GButton resume1; 
GButton save1;
GButton filter1;


